### ISSUE TITLE
Default configuration results in The organization you were looking for was not found.

### ISSUE THREAD

**Issue by do3cc** [SkyLothar/sentry-auth-gitlab#1]
And I have no idea, where to look yet :-(

**Comment by do3cc** [comment]
My mistake, I did NOT follow the readme properly,

I filled the `GITLAB_BASE_DOMAIN` with the base domain of sentry itself. doh.

**Comment by SkyLothar** [comment]
:smile:  let me know if you have more questions

**Comment by do3cc** [comment]
Thanks!
Got it working finally :-)
