### ISSUE TITLE
Gitlab 9.2.2 seems to requires api SCOPE instaed of read_user

### ISSUE THREAD

**Issue by tuco86** [SkyLothar/sentry-auth-gitlab#5]
when i updated my gitlab, sentry-oauth was not working anymore.. i fixed it when i changed the scope in constants.py to 'api'

**Comment by SkyLothar** [comment]
Thanks! I'll see what I can do to fix this problem. 🤔

**Comment by chrisblech** [comment]
see #7

**Comment by SkyLothar** [comment]
Thanks @tuco86 @chrisblech , v0.1.0 should plays well with gitlab 9.x installations.
