### ISSUE TITLE
Bad Request (400) after Gitlab Authorize

### ISSUE THREAD

**Issue by kpyorala** [SkyLothar/sentry-auth-gitlab#6]
When I click `Authorize` in Gitlab I'm redirected to address `https://sentry.my.domain/auth/sso/?code=xxx&state=yyy` and I get error `Bad Request (400)`. No more information in logs. I tested to change `constants.py` from `read_user` to `api` as proposed in other issue, but it didn't help either. Any ideas how to search more information of the problem?

Gitlab version 9.2.1-ee (Docker),  Sentry version 8.16.0 (Docker)

**Comment by SkyLothar** [comment]
Hi, v0.1.0 has been tested with GitlabCE 9.2.2 (Docker) and Sentry 8.1.6 (Docker).
Would you please try out the latest version with your installation and give me a feedback?

**Comment by DenisKuplyakov** [comment]
I have tried with GitlabCE 9.3.2 and Sentry 8.17 (Docker) just now and also got this error.

**Comment by DenisKuplyakov** [comment]
I've solved problem. GitLab IP was in SENTRY_DISALLOWED_IPS list, I've removed another line instead of needed one.

**Comment by SkyLothar** [comment]
Everything should workd
